name: 'GHA Rabbit MQ Sender'
description: 'Sends a message to rabbitmq'
inputs:
  projectType:
    description: 'Project type (NetFramework, NetCore, GoLang)'
    required: true
  projectName:
    description: 'Project name'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'